const express = require('express')
const router = express.Router()
const {topBooks,adminNotification,UserRejectedRequestData,UserData,UserExpiredApprovalsData,UserApprovedRequestData,returnedBooks,RecentActvity,BorrowedBooks,UserpendingRequestData,rejectedRequetsData,expiredApprovalsData,requestCount,borrowedRequestCount,overDueCount,membersActivity,approvedRequestsData} = require("../controller/BorrowDataController")
const Token_Verfication = require("../middleware/authMiddleware")
router.get("/topBooks",Token_Verfication,topBooks)
router.get("/adminNotification",Token_Verfication,adminNotification)
router.get("/UserpendingRequestData",Token_Verfication,UserpendingRequestData)
router.get("/UserApprovedRequestData",Token_Verfication,UserApprovedRequestData)
router.get("/UserRejectedRequestData",Token_Verfication,UserRejectedRequestData)
router.get("/UserExpiredApprovalsData",Token_Verfication,UserExpiredApprovalsData)
router.get("/requestCount",Token_Verfication,requestCount)
router.get("/borrowedRequestCount",Token_Verfication,borrowedRequestCount)
router.get("/overDueCount",Token_Verfication,overDueCount)
router.get("/membersActivity",Token_Verfication,membersActivity)
router.get("/approvedRequestsData",Token_Verfication,approvedRequestsData)
router.get("/expiredApprovalsData",Token_Verfication,expiredApprovalsData)
router.get("/rejectedRequetsData",Token_Verfication,rejectedRequetsData)
router.get("/BorrowedBooks",Token_Verfication,BorrowedBooks)
router.get("/returnedBooks",Token_Verfication,returnedBooks)
router.get("/RecentActvity",Token_Verfication,RecentActvity)
router.get("/UserData",Token_Verfication,UserData)
module.exports = router